# -*- coding: utf-8 -*-
"""docs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fg32_yXiN94GgzUJzMX3MkxpspHzYgpr
"""

!pip install sphinx
!sphinx-build --version

!sphinx-quickstart docs